### ISSUE TITLE
gen_rootfs submodule is broken

### ISSUE THREAD

**Issue by d3zd3z** [linaro-swg/hikey_optee#1]
Upon checking this out, and doing a submodule update, I get

```
% git submodule update              /mnt/linaro/optee/hikey_optee
fatal: reference is not a tree: 6193379c6558613fa56289ed3d1a94c850ae0cf0
Unable to checkout '6193379c6558613fa56289ed3d1a94c850ae0cf0' in submodule path 'gen_rootfs'
```

and the gen_rootfs directory is empty. Did something get missed pusing to gen_rootfs.git?

**Comment by jockebech** [comment]
Hi David,

Jerome will probably fill in, I'd just want to mention that even though I think Jerome's tree usually works fine it's still the unofficial way of getting the code for HiKey (for use with OP-TEE). The method we tell to the public is the one mentioned in optee_os/[README.md](https://github.com/OP-TEE/optee_os/blob/master/README.md). The steps that you need to follow there are usually, 4.1, 5.1, 5.2 and then finally 5.5 for HiKey. This was tested yesterday when we released, so hopefully that should still work.

**Comment by jforissier** [comment]
Indeed, `gen_rootfs` was pointing to a private commit. Should be fixed now.

**Comment by vchong** [comment]
Fixed here: https://github.com/linaro-swg/hikey_optee/commit/9ca426f30cde5ccab509c2922df98106a39068d5
